### PR TITLE
Feat/toast notifications

### PR DESCRIPTION
**Pull request by sarthak22gaur**
## Overview

Initial implementation for #366 

- Toast notification for creating and deleting year, adding, moving semesters.
- Currently uses default styling provided by react-toastify.

**This is a test implementation and does not use the existing notification setup. That is something that needs to looked into and possibly integrated with toastify.**

### CODE REVIEW

**Review by thekevinge — CHANGES_REQUESTED** [review]
Looks good! I'm glad you brought up react-toastify. Just a nitpick. Can you remove ToastMessage from ``components/planner/types.ts`` and remove the ``then(notification => ..)`` from the callbacks in ``components/planner/Planner.tsx``

**Comment by sarthak22gaur** [comment]
I was thinking of using the callbacks in some way if possible, if not, then I'll remove those.

**Comment by sarthak22gaur** [comment]
Changed the implementation to use the existing notification message for promise resolves. However this does not show loading state while promise is resolving, just the final notification on resolve.
Need to add the same for promise rejects.

**Comment by thekevinge** [comment]
> Changed the implementation to use the existing notification message for promise resolves. However this does not show loading state while promise is resolving, just the final notification on resolve. Need to add the same for promise rejects.

Do you think it would be better to show a pending promise state and a resolved/rejected state as you had it initially? I'd love to hear @jasonappah's opinion on this too.

> I was thinking of using the callbacks in some way if possible, if not, then I'll remove those.

Can you elaborate a bit on this? Why do you think we should use the callbacks? When I implemented those, I did it solely for the toast notifications, but I'd like to hear what you think.

Hopefully, I'm not nitpicking too much!

**Comment by sarthak22gaur** [comment]
> Do you think it would be better to show a pending promise state and a resolved/rejected state as you had it initially?

I also liked it better with the pending and resolved/reject states. But that occurs when the promise is resolved in the tRPC mutation, and not when the task queue is updated. Because of this, the notification is delayed from the user's perspective.
Also, the notification level information from the ToastMessage is lost as it does not get propagated to the tRPC handler.

> Can you elaborate a bit on this? Why do you think we should use the callbacks? 

to make use of the ToastMessage level warning states. Toastify docs mention a way that allows using the promise return values for the conditional rendering of the toast. I'll be looking into it today.

I think this will go through a few more iterations before we can arrive at the final solution as there are a lot more things to still add, especially the error states. 🙃

**Comment by sarthak22gaur** [comment]
1. Using pending and resolve toast for mutations and simple notification for warnings. 
2. Removed the callbacks, moved all handlers inside `Planner.tsx`

**Review by thekevinge — APPROVED** [review]
LGTM

**Review by ZzRanger — APPROVED** [review]
LGTM!

**Pull request merged**
